export const cardItems = [
    {
        "id": "1",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #1",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #1",
        "develop_price": 17500,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17000,
    },
    {
        "id": "2",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #2",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #2",
        "develop_price": 17600,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17100,
    },
    {
        "id": "3",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #3",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #3",
        "develop_price": 17700,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17200,
    },
    {
        "id": "4",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #4",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #4",
        "develop_price": 17800,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17300,
    },
    {
        "id": "5",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #5",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #5",
        "develop_price": 17900,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17400,
    },
    {
        "id": "6",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #6",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #6",
        "develop_price": 18000,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17500,
    },
    {
        "id": "7",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #7",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #7",
        "develop_price": 18100,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17600,
    },
    {
        "id": "8",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #8",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #8",
        "develop_price": 18200,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17700,
    },
    {
        "id": "9",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #9",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #9",
        "develop_price": 18300,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17800,
    },
    {
        "id": "10",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #10",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #10",
        "develop_price": 18400,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 17900,
    },
    {
        "id": "11",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #11",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #11",
        "develop_price": 18500,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18000,
    },
    {
        "id": "12",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #12",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #12",
        "develop_price": 18600,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18100,
    },
    {
        "id": "13",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #13",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #13",
        "develop_price": 18700,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18200,
    },
    {
        "id": "14",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #14",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #14",
        "develop_price": 18800,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18300,
    },
    {
        "id": "15",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #15",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #15",
        "develop_price": 18900,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18400,
    },
    {
        "id": "16",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #16",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #16",
        "develop_price": 19000,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18500,
    },
    {
        "id": "17",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #17",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #17",
        "develop_price": 19100,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18600,
    },
    {
        "id": "18",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #18",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #18",
        "develop_price": 19200,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18700,
    },
    {
        "id": "19",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #19",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #19",
        "develop_price": 19300,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18800,
    },
    {
        "id": "20",
        "image": "https://i.ibb.co/sHqPvD6/photo-2.png",
        "name": "Фотобудка с ширмой #20",
        "size": "2м x 1.5м x 2 м",
        "develop": "Разработка макета рамки #20",
        "develop_price": 19400,
        "develop_image": "https://i.ibb.co/P1Q2H8K/photo-option.png",
        "price": 18900,
    }
]